### ISSUE TITLE
k8s: kubectl port forwarding for vtctld is not working

### ISSUE THREAD

**Issue by gosharplite** [youtube/vitess#1280]
Just run the latest scripts and I can access vtctld web UI beautifully. 

The kubectl port forwarding seems to work since I manually run each command in start_vtctld_forward() of  env.sh script. The `vtctld_forward_port` is found and changes value each time as expected.

I suspect something strange happens in vtctlclient when below command is executed.
`vtctlclient -server localhost:$vtctld_forward_port "$@"`

```
$ ./kvtctl.sh help
Starting port forwarding to vtctld...
2015/11/04 16:07:32 transport: http2Client.notifyError got notified that the client transport was broken EOF.
E1104 16:07:32.277176   11446 main.go:49] Remote error: rpc error: code = 13 desc = "transport is closing"
2015/11/04 16:07:32 grpc: ClientConn.transportMonitor exits due to: grpc: the client connection is closing
```

**Comment by gosharplite** [comment]
A workaround is to expose grpc through nodePort, and bypass kubectl port forwarding.
```
$ vtctlclient -server 10.128.112.25:30032 help
Available commands:

Tablets:
  InitTablet [-allow_update] [-allow_different_shard] [-allow_master_override] [-parent] [-db_name_override=<db name>] [-hostname=<hostname>] [-mysql_port=<port>] [-port=<port>] [-grpc_port=<port>] -keyspace=<keyspace> -shard=<shard> <tablet alias> <tablet type>
  GetTablet <tablet alias>
  UpdateTabletAddrs [-hostname <hostname>] [-ip-addr <ip addr>] [-mysql-port <mysql port>] [-vt-port <vt port>] [-grpc-port <grpc port>] <tablet alias> 
  DeleteTablet [-allow_master] [-skip_rebuild] <tablet alias> ...
```
Here is my `vtctld-service.yaml`.
```
kind: Service
apiVersion: v1
metadata:
  name: vtctld
  labels:
    component: vtctld
    app: vitess
spec:
  ports:
    - name: web
      port: 15000
      nodePort: 30030
    - name: grpc
      port: 15999
      nodePort: 30032
  selector:
    component: vtctld
    app: vitess
  type: NodePort
```
